phpmob_sylius_bank_payment_plugin_admin_account:
    type: sylius.resource
    resource: |
        alias: phpmob.account
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: index
        grid: grid_admin_phpmob_account
        permission: true
        vars:
            all:
                templates:
                    form: "@PhpMobSyliusBankPaymentPlugin/Admin/Account/_form.html.twig"
