phpmob_sylius_bank_payment_plugin_admin_transaction:
    type: sylius.resource
    resource: |
        alias: phpmob.transaction
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: index
        grid: grid_admin_phpmob_transaction
        permission: true
        vars:
            all:
                templates:
                    form: "@PhpMobSyliusBankPaymentPlugin/Admin/Transaction/_form.html.twig"

phpmob_admin_transaction_approve:
    path: /transactions/{id}/{type}/{comment}
    methods: [GET]
    defaults:
        comment: ''
        _controller: phpmob.controller.transaction:applyStateMachineTransitionAction
        _sylius:
            event: approve
            permission: true
            csrf_protection: false
            redirect: referer
            state_machine:
                graph: phpmob_transaction
                transition: $type
