phpmob_sylius_bank_payment_plugin_admin_transaction:
    type: sylius.resource
    resource: |
        alias: phpmob.transaction
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: index
        grid: grid_admin_phpmob_transaction
        permission: true
        vars:
            all:
                templates:
                    form: "@PhpMobSyliusBankPaymentPlugin/Admin/Transaction/_form.html.twig"
